### ISSUE TITLE
Mission attributes update

### ISSUE THREAD

**Issue by Mate2xo** [Mate2xo/THP-Creeons_la_coop#178]
Duty periods Mission at the shop have recurrent  informations. They will be put into their own fields

## Tasks to do when mission starts

- [ ] `to_do_on_start`
- [ ] add related field on `missions/_form.html`
- [ ] add related section on `missions/show.html` if filled

## Tasks to do when mission ends

- [ ] `to_do_on_end`
- [ ] add related field on `missions/_form.html`
- [ ] add related section on `missions/show.html` if filled

**Comment by Mate2xo** [comment]
Closing, as it ended being unnecessary
